### ISSUE TITLE
Empty module configuration

### ISSUE THREAD

**Issue by nrunde** [heimrichhannot/contao-multifileupload#1]
After installing your extension, there are is an empty label in module type select and also there are no fields to configure the module. 
Contao is on version 3.5.8
Installation via composer

**Comment by Defcon0** [comment]
At the moment, the plugin only works with our extension formhybrid. Form generator support is planned though.

**Comment by nrunde** [comment]
Ok, I didn't get that. Are the any final plan or dues when you will implement support for form generator?

**Comment by Defcon0** [comment]
Since we're quite full with projects it could take a while, i.e. some weeks.

**Comment by nrunde** [comment]
Ok. Thanks for fast response.
