### ISSUE TITLE
Uncaught Error after update

### ISSUE THREAD

**Issue by basistom** [heimrichhannot/contao-multifileupload#2]
After updating Chrome shows the following error in the frontend (Contao 3.5.12):

`*-collection.js:4034 Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function`

Which is caused by a missing semikolon in dropzone.js in line 1801.

**Comment by Defcon0** [comment]
dropzone.js is not part of multifileupload. Hence you should refer to that issue on contao core repo ;)

**Comment by basistom** [comment]
You are absolutly right ;) 
At least using the minified dropzone.js in your config solves the bug for me.

`$GLOBALS['TL_JAVASCRIPT']['dropzone'] = 'assets/dropzone/' . $GLOBALS['TL_ASSETS']['DROPZONE'] . '/js/dropzone.min.js';`
