### ISSUE TITLE
Kein Formfeld Multifile-Upload in Contao 3.5.15

### ISSUE THREAD

**Issue by basistom** [heimrichhannot/contao-multifileupload#3]
Contao 3.5.15
/heimrichhannot/contao-formhybrid ist hinzugefügt

Im Dropdown zur Feldtyp-Auswahl gibt es kein Feld für den Multifile-Upload.

**Comment by fatcrobat** [comment]
contao-multifileupload funktioniert aktuell nicht mit dem Contao Formgenerator, sondern dient ausschließlich als Widget für den Dateiupload innerhalb von Formhybrid. Pull Requests sind gern gesehen.
