### ISSUE TITLE
Can't upload files with special characters

### ISSUE THREAD

**Issue by krypta83** [heimrichhannot/contao-multifileupload#4]
If you upload files with special characters (spaces for example), the upload fails! If you remove the spaces and restart the upload, all works fine. 
Tested with Contao 3.5.17

**Comment by fatcrobat** [comment]
What version of multifileupload you use? No idea why i get notified of this issue by github first today, so hopefully the issue dont exist any more for the latest version.

**Comment by fatcrobat** [comment]
Closed, no feedback.
