### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by barrystaes** [heimrichhannot/contao-multifileupload#5]
Sorry in advance because i must be missing something obvious, but how to install? (Contao 3.5.24)

I found no installation instructions, and its not listed in the Extension Catalog either. Same goes for other extensions you have here like **datamap** and **slick**, they look great and i would like to try them.

**Comment by fatcrobat** [comment]
Simply use the contao composer extension and search for the composer name of our modules, like heimrichhannot/contao-multifileupload and install it. Another way is to install via console/terminal, dir into contao/composer and run `composer require heimrichhannot/contao-multifileupload`. List of all of our public extensions can be found here https://packagist.org/search/?q=heimrichhannot.

We dont support the old installation through the old contao extension repository.

**Comment by ameotoko** [comment]
Is it possible to install the extension **without** switching to Composer Extension?
I'm using a commercial module which doesn't support composer.
I have Composer CLI available on my server though.

**Comment by fatcrobat** [comment]
We do not recommend this, as you do not have any update functionality. 

If you ignore this notice, install manually the following modules to the declared locations:

- **heimrichhannot/contao-ajax** -> system/modules/ajax
- **heimrichhannot/dropzone4** -> assets/dropzone4
- **heimrichhannot/contao-components** -> system/modules/components
- **heimrichhannot/contao-multifileupload** -> system/modules/multifileupload

You will find these packages https://packagist.org/.
