### ISSUE TITLE
Kompatibilität mit 4.4.3

### ISSUE THREAD

**Issue by sebssch** [heimrichhannot/contao-multifileupload#6]
Gerade über den Contao Manager installiert.
Installation klappt reibungslos. 
Leider werden die Datenbankfelder über das Installtool nicht angelegt.

Wird die Erweiterung an Contao 4.4 + Contao Manager geupdatet?

**Comment by fatcrobat** [comment]
Hallo,

das Modul bringt keine eigenen Datenbankfelder mit sich, daher kann es auch keine Datenbankfelder anlegen. Ein inputtyp `multifileupload` sollte über ein Sql-Definition `'sql'       => "blob NULL"` verfügen und dann legt Contao das Feld auch entsprechend an. Cache leeren nicht vergessen.

Ja, wir bieten Contao Support für diese Erweiterung. 

Ich schließe das Ticket vorerst. Sollten weitere Probleme auftretet, Ticket bitte erneut öffnen.
