### ISSUE TITLE
Cannot update or install via Composer

### ISSUE THREAD

**Issue by ghost** [heimrichhannot/contao-multifileupload#8]
Hi,

I am not able to install or update this plug-in. This is the log. It seems something is broken. I tried going down to 1.2*. Always the same exception.

 - Installing heimrichhannot/contao-multifileupload (1.3.2): Downloading (100%)
    Failed to download heimrichhannot/contao-multifileupload from dist: There was an error extracting the ZIP file, it is either corrupted or using an invalid format.
    Now trying to download from source
  - Installing heimrichhannot/contao-multifileupload (1.3.2): Cloning 9d0e093a1d from cache
    9d0e093a1dba303c84cfc14ce92b32e2205a4844 is gone (history was rewritten?)

  [RuntimeException]
  Failed to execute git checkout "9d0e093a1dba303c84cfc14ce92b32e2205a4844" -- && git reset --hard "9d0e093a1dba303c84cfc14ce92b32e2205a4844" --
  HEAD is now at 9d0e093... fixed popup route error in contao 4
  error: unable to create file test/files/.~file   name#%&*{}:<>?+|"'.zip: Invalid argument
  fatal: Could not reset index file to revision '9d0e093a1dba303c84cfc14ce92b32e2205a4844'.

**Comment by K0NZ1** [comment]
@svenja-poniecki 
Are you using Windows?
Probably Windows cant handle the special file names of the test files.

I fixed this by generating the test files with special names when executing the test for the first time. Hopefully it fixed your problem.

**Comment by ghost** [comment]
Yes, windows and yes, you fixed it. Thanks a lot!
