### ISSUE TITLE
Form Field not loaded in Backend

### ISSUE THREAD

**Issue by joeherold** [heimrichhannot/contao-multifileupload#9]
Tried this module in Contao 4.4.8
The backend Form-Field is not loaded. I guess this is a problem with the tl_form_field DCA definition? I cleared dev and prod cache, no difference.
![bildschirmfoto 2017-12-05 um 01 24 03](https://user-images.githubusercontent.com/3911545/33583504-053dd9c0-d95b-11e7-93dd-c1b183fed304.png)

![bildschirmfoto 2017-12-05 um 01 24 43](https://user-images.githubusercontent.com/3911545/33583521-184872b4-d95b-11e7-95b6-82315d957d15.png)

**Comment by Defcon0** [comment]
Currently we do not provide support for Contao form generator. Only usage in combination with https://github.com/heimrichhannot/contao-formhybrid is provided at the moment.

**Comment by joeherold** [comment]
ok, got it. thank you
